version: "3.8"

services:    
    sql-server-aspirepoc:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sql-server-aspirepoc
        ports:
          - 1433:1433
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"       
        volumes:
          - /mnt/c/Linux/mssql/data:/var/opt/mssql/data
          - /mnt/c/Linux/mssql/log:/var/opt/mssql/log
          - /mnt/c/Linux/mssql/secrets:/var/opt/mssql/secrets
        command: /opt/mssql/bin/sqlservr

    rabbitmq-aspirepoc:
      image: "rabbitmq:3.8-management"
      container_name: rabbitmq-aspirepoc
      ports:
        - "5672:5672"  # RabbitMQ default port
        - "15672:15672"  # RabbitMQ management console port
      environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
    driver: local
